name: Build pipeline with security test
on:
  push:
  repository_dispatch:
  workflow_dispatch:

jobs:
  scan:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Run VAmPI 
        run: docker compose up -d
        
      - name: Test VAmPI
        run: sleep 5 && curl http://localhost:5001/ --retry 10 --retry-delay 1  
        
      - name: Docker login
        uses: docker/login-action@v1 
        with:
          registry: jfrog.cicd.nonamesec.com/noname-docker-release
          username: ${{ secrets.ACTIVE_REGISTRY_USER }} 
          password: ${{ secrets.ACTIVE_REGISTRY_PASSWORD }}
      
      - name: Active Testing Scan
        run: >
          docker run 
          --add-host=host.docker.internal:host-gateway 
          -e ACTIVE_CONFIG_FILE_PATH=/noname/config.json 
          -v $(pwd)/noname:/noname 
          -v $(pwd)/openapi_specs:/openapi_specs 
          jfrog.cicd.nonamesec.com/noname-docker-release/active-cli:$(curl -k ${{secrets.ACTIVE_API_URL}}/backend/version) scan 
          --api-url=${{ secrets.ACTIVE_API_URL }} 
          --api-token=${{ secrets.ACTIVE_API_TOKEN }} 
          --test-group-id=62f5921c-d200-4f6f-a104-29674ad30a94
          --branch-name=${{ github. head_ref || github. ref_name }}
          --severity-threshold=none
  deploy:
    needs: scan 
    runs-on: ubuntu-latest 
    steps:
      - name: echo
        run: echo Security scan passed, deploying to production